//
// Generated file, do not edit! Created by opp_msgtool 6.0 from pkt.msg.
//

#ifndef __PKT_M_H
#define __PKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Pkt;
/**
 * Class generated from <tt>pkt.msg:3</tt> by opp_msgtool.
 * <pre>
 * packet Pkt
 * {
 *     simtime_t genTime;
 *     int number;
 * }
 * </pre>
 */
class Pkt : public ::omnetpp::cPacket
{
  protected:
    omnetpp::simtime_t genTime = SIMTIME_ZERO;
    int number = 0;

  private:
    void copy(const Pkt& other);

  protected:
    bool operator==(const Pkt&) = delete;

  public:
    Pkt(const char *name=nullptr, short kind=0);
    Pkt(const Pkt& other);
    virtual ~Pkt();
    Pkt& operator=(const Pkt& other);
    virtual Pkt *dup() const override {return new Pkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual omnetpp::simtime_t getGenTime() const;
    virtual void setGenTime(omnetpp::simtime_t genTime);

    virtual int getNumber() const;
    virtual void setNumber(int number);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Pkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Pkt& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Pkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<Pkt*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PKT_M_H

